import { RoomItem } from "./types";

export const roomsData: RoomItem[] = [
  {
    id: "1",
    name: "Premium Double Room",
    category: "double",
    location: "Ramapuram, Chennai",
    area: "Ramapuram",
    price: 13500,
    deposit: 5000,
    photoCount: 5,
    image: "/images/rooms/room_single.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "2",
    name: "Twin Sharing Room",
    category: "double",
    location: "Ramapuram, Chennai",
    area: "Ramapuram",
    price: 11500,
    deposit: 5000,
    photoCount: 3,
    image: "/images/rooms/room_deluxe.png",
    amenities: { wifi: true, food: false, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "3",
    name: "Triple Sharing Room",
    category: "triple",
    location: "Madanandapuram, Chennai",
    area: "Madanandapuram",
    price: 10500,
    deposit: 5000,
    photoCount: 4,
    image: "/images/rooms/room_sharing.png",
    amenities: { wifi: true, food: false, ac: false, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "4",
    name: "Private Room",
    category: "private",
    location: "Madanandapuram, Chennai",
    area: "Madanandapuram",
    price: 10200,
    deposit: 5000,
    photoCount: 7,
    image: "/images/rooms/room_comfort.png",
    amenities: { wifi: true, food: false, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "5",
    name: "Standard Double Room",
    category: "double",
    location: "Madanandapuram, Chennai",
    area: "Madanandapuram",
    price: 10500,
    deposit: 5000,
    photoCount: 12,
    image: "/images/rooms/room_single.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "6",
    name: "Deluxe Single Room",
    category: "single",
    location: "Anna Nagar, Chennai",
    area: "Anna Nagar",
    price: 14000,
    deposit: 6000,
    photoCount: 8,
    image: "/images/rooms/room_deluxe.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "7",
    name: "Premium Single Room",
    category: "single",
    location: "Anna Nagar, Chennai",
    area: "Anna Nagar",
    price: 15500,
    deposit: 7000,
    photoCount: 6,
    image: "/images/rooms/room_single.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "8",
    name: "Executive Private Room",
    category: "private",
    location: "Guindy, Chennai",
    area: "Guindy",
    price: 16000,
    deposit: 8000,
    photoCount: 9,
    image: "/images/rooms/room_comfort.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "9",
    name: "Comfort Twin Sharing",
    category: "double",
    location: "Guindy, Chennai",
    area: "Guindy",
    price: 11000,
    deposit: 5000,
    photoCount: 5,
    image: "/images/rooms/room_sharing.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "10",
    name: "Budget Triple Sharing",
    category: "triple",
    location: "Velachery, Chennai",
    area: "Velachery",
    price: 9000,
    deposit: 4000,
    photoCount: 4,
    image: "/images/rooms/room_sharing.png",
    amenities: { wifi: true, food: true, ac: false, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "11",
    name: "Deluxe Triple Room",
    category: "triple",
    location: "Velachery, Chennai",
    area: "Velachery",
    price: 9800,
    deposit: 4500,
    photoCount: 5,
    image: "/images/rooms/room_comfort.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "12",
    name: "Standard Single Room",
    category: "single",
    location: "Porur, Chennai",
    area: "Porur",
    price: 12000,
    deposit: 5000,
    photoCount: 5,
    image: "/images/rooms/room_deluxe.png",
    amenities: { wifi: true, food: true, ac: true, laundry: false, housekeeping: true },
    availableNow: true,
  },
  {
    id: "13",
    name: "Comfort Single Room",
    category: "single",
    location: "Porur, Chennai",
    area: "Porur",
    price: 12800,
    deposit: 5500,
    photoCount: 6,
    image: "/images/rooms/room_single.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "14",
    name: "Luxury Private Room",
    category: "private",
    location: "Anna Nagar, Chennai",
    area: "Anna Nagar",
    price: 18000,
    deposit: 8000,
    photoCount: 10,
    image: "/images/rooms/room_comfort.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "15",
    name: "Classic Double Room",
    category: "double",
    location: "Porur, Chennai",
    area: "Porur",
    price: 10800,
    deposit: 5000,
    photoCount: 4,
    image: "/images/rooms/room_sharing.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "16",
    name: "Standard Triple Room",
    category: "triple",
    location: "Ramapuram, Chennai",
    area: "Ramapuram",
    price: 9500,
    deposit: 4000,
    photoCount: 4,
    image: "/images/rooms/room_sharing.png",
    amenities: { wifi: true, food: true, ac: true, laundry: false, housekeeping: true },
    availableNow: true,
  },
  {
    id: "17",
    name: "Studio Private Room",
    category: "private",
    location: "Guindy, Chennai",
    area: "Guindy",
    price: 16500,
    deposit: 7000,
    photoCount: 8,
    image: "/images/rooms/room_single.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
  {
    id: "18",
    name: "Cozy Double Sharing",
    category: "double",
    location: "Velachery, Chennai",
    area: "Velachery",
    price: 11200,
    deposit: 5000,
    photoCount: 5,
    image: "/images/rooms/room_deluxe.png",
    amenities: { wifi: true, food: true, ac: true, laundry: true, housekeeping: true },
    availableNow: true,
  },
];
